# Generated by Django 4.1.5 on 2023-01-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_alter_clock_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
