# Generated by Django 4.1.5 on 2023-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_alter_clock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='has_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
